- name:  Create a new primary partition for LVM
  parted:
    device: "{{ device1_path }}"
    number: 1
    flags: [ lvm ]
    state: present
    part_type: primary
    part_start: 0%
    part_end: 100%
